### ISSUE TITLE
Adding a license 

### ISSUE THREAD

**Issue by noknokcody** [HardeepAsrani/my-awesome-plugin#16]
Hi there,

I'd love to use some of your code snippets in my project but I don't want to do so without permission or a license.

Would you mind adding a license like MIT to your project?

Cheers!

**Comment by HardeepAsrani** [comment]
Hey @noknokcody,

I've defined the license type in index.php. All my code is under GPL-v3 or related open source licenses. Feel free to use any of my code anywhere, nothing I code is ever closed source. :)

**Comment by noknokcody** [comment]
Thanks mate, your work has been a huge help!
