### ISSUE TITLE
How to combine it with my gutenberg plugin?

### ISSUE THREAD

**Issue by ZafarKamal123** [HardeepAsrani/my-awesome-plugin#2]
I want to integrate an option page in my **Gutenberg Plugin** made with react app, In your example you've simply created a single plugin, Like in my case i want to merge an option page with my existing wordpress plugin?

**Comment by HardeepAsrani** [comment]
@ZafarKamal123 Then you will just do the same just not set it up as a new plugin. You will register the settings and then add the code to the source file.

**Comment by HardeepAsrani** [comment]
@ZafarKamal123 Then you will just do the same just not set it up as a new plugin. You will register the settings and then add the code to the source file.

**Comment by ZafarKamal123** [comment]
The thing is, I've tried everything you did. I created a block using create guten block and it is hard to make both work, Can you help me with this?

**Comment by HardeepAsrani** [comment]
Just try adding this file in your JS file: https://github.com/HardeepAsrani/my-awesome-plugin/blob/master/src/index.js

**Comment by ZafarKamal123** [comment]
I did try that, It throws an error of block registerations

**Comment by HardeepAsrani** [comment]
@ZafarKamal123 What error exactly?

**Comment by HardeepAsrani** [comment]
Closing as it's inactive. You can reopen if you want.
