### ISSUE TITLE
Notification and multiple inputs

### ISSUE THREAD

**Issue by Mecanik** [HardeepAsrani/my-awesome-plugin#20]
Hi! Thanks for the awesome example.

I`m not so well versed with React or WP components, how would I add a notification upon save? I tried a few examples online but frankly wasted hours and nothing worked, lol.

Also, if I add multiple inputs... how can I save all "at once"? For example besides analytics key input, I would like to add another one.

Many Thanks!

**Comment by HardeepAsrani** [comment]
Hey @Mecanik,

You can use a component like this for adding notifications: https://www.npmjs.com/package/react-notifications-component

You can just do what we did in our example just add a save button that sends both the input values at the same time. We do something similar here: https://github.com/Codeinwp/otter-blocks/blob/master/src/dashboard/Components/Main.js#L274-L317

**Comment by Mecanik** [comment]
Thanks a lot.
